[colors.primary]
background = "#282828"
foreground = "#ebdbb2"
dim_foreground = "#bdae93"
bright_foreground = "#ebdbb2"

[colors.cursor]
text = "#282828"
cursor = "#d5c4a1"

[colors.vi_mode_cursor]
text = "#282828"
cursor = "#d79921"

[colors.search.matches]
foreground = "#282828"
background = "#d79921"

[colors.search.focused_match]
foreground = "#282828"
background = "#98971a"

[colors.footer_bar]
foreground = "#282828"
background = "#d79921"

[colors.hints.start]
foreground = "#282828"
background = "#fabd2f"

[colors.hints.end]
foreground = "#282828"
background = "#d79921"

[colors.selection]
text = "#282828"
background = "#d5c4a1"

[colors.normal]
black = "#282828"
red = "#cc241d"
green = "#98971a"
yellow = "#d79921"
blue = "#458588"
magenta = "#b16286"
cyan = "#689d6a"
white = "#a89984"

[colors.bright]
black = "#928374"
red = "#fb4934"
green = "#b8bb26"
yellow = "#fabd2f"
blue = "#83a598"
magenta = "#d3869b"
cyan = "#8ec07c"
white = "#ebdbb2"

[colors.dim]
black = "#928374"
red = "#cc241d"
green = "#98971a"
yellow = "#d79921"
blue = "#458588"
magenta = "#b16286"
cyan = "#689d6a"
white = "#a89984"

[[colors.indexed_colors]]
index = 16
color = "#d79921"

[[colors.indexed_colors]]
index = 17
color = "#ebdbb2"
